### ISSUE TITLE
[Help] Issues getting Jorian to work

### ISSUE THREAD

**Issue by geoah** [joric/jorian#1]
Hey there; first of all thank you for open sourcing this design, the design is just amazing and the fact it's a 100x100 makes it even more awesome!

---

I've printed the 1.0 release PCBs and simply soldered some YJ-14015s and some switched on them.
For now I've skipped all solder jumpers and I'm powering the boards through the SWD connector.

I've tried flashing these three with both an stlink:
* your pre-compiled bluetosis firmware from your releases
* the bluetosis firmware from your `jorian` branch
* the qmk firmware from your `nrf5x` branch

also I'm always flashing `s130_nrf51_2.0.1_softdevice` just for good measure.

___But I'm always having the same issue:___
When I first flash the keyboard, I can see the device broadcasting the correct name, I try to connect to it, it shows as connected, and within a couple of seconds it disconnects and never shows up again.

The only way to get it to show up again is re-flashing it or resetting it.
After that, same thing happens. Shows up. Connects. Dies.

__Is there something very obvious I'm missing? Have I completely forgotten to do something?__

---

ps. I've converted my blue pill into a black magic, and I'm trying to use it to debug the board, but nothing seems to show up. (I'll keep trying to get debugging to work for now)

pps. I do apologise if this is the wrong place to ask for this king of help/support, and I wanted to thank you again for all the hard work you've done with joria, bluetosis, and now the nrf fork of qmk and nrfmicro.

ppps. 
![IMG_1299](https://user-images.githubusercontent.com/88447/56685091-092e4e00-66c9-11e9-8d4a-ada7e69d8b9f.jpg)

Thank you very much in advance.

**Comment by joric** [comment]
## Bluetosis

Nordic chip pairing is a bit weird. You need to reset all bonds first, then it should pair and connect just fine (to reset bonds, hold a special key while powering on, I don't remember which one, see keyboard shortcuts).

The Bluetosis firmware is really shitty I wouldn't really consider it, hope it gets obsolete when I manage to run nRF5x branch.

## nRF5x branch

I'm currently working on nRF5x branch, and you just gave me a boost (also I have a few keyboards just laying around without a properly working firmware, from that 10 PCBs pack I got from Elecrow).

The nRF5x branch is quite problematic, not sure it will ever work. There are 2 modules with this pinout:

* [Core51822B](https://www.aliexpress.com/item/Core51822-B-BLE4-0-Bluetooth-2-4G-Wireless-Module-nRF51822-Onboard-Rev3-features-32kB-RAM-supports/32374207080.html) (QFAC, 32K RAM)
* [YJ-14015](https://www.aliexpress.com/item/-/32832872640.html) (QFAA, 16K RAM)

I only have the latter, so I'm trying to run everything with 16K RAM. If you're using 32K module you could try stock `ble_master.c` instead of my (non-working) `ble_master_lowmem.c` (set `NRF_MASTER_LOWMEM = no`):

* https://github.com/joric/qmk_firmware/tree/nrf5x/keyboards/mitosis_ble (it's actually jorian layout)

Also see nRF5x pairing tips here:

* https://github.com/joric/nrfmicro/wiki/Jian-BLE

If you're writing an article I strongly suggest writing about Jian as well, because my keyboard is basically a shameless Jian ripoff: 

# [Jian GB thread, BUY MORE JIAN!](https://redd.it/bfnd9k)

## Mitosis firmware and Mitosis receiver

You can also try mitosis firmware and mitosis receiver for now, it should work just fine: 

* https://github.com/joric/qmk_firmware/tree/mitosis-jorian/rykeyboards/mitosis/keymaps/jorian

There is a precompiled version in the releases, it's the only production quality firmware and it's for mitosis receiver only:

* https://github.com/joric/jorian/releases

To use it you need to flash jorian halves with stock MITOSIS firmware (it's covered in the readme here, read carefully):

* https://github.com/joric/jorian

(It has no ws2812 LEDs support though, but there's plenty of room for that since it's not using softdevice).

## Misc

I messed up charger jumpers so the right half should be soldered like this, if you're using a charger: 

![](https://i.imgur.com/uGkheMR.jpg)

USB GND should be disconnected, I guess (the charger uses pass-through BAT+ and switchable GND).

Charger has NO source select, only protection (good for lir2032), so you'd need Li-Po for VCC and for LEDs.

Should've added more disclaimers, but hey, it's still a valid Mitosis clone in a 100x100 PCB.

KLE for hardware layout, could be useful (S1-S22 is mitosis key mapping, sideprint is LED order):

http://www.keyboard-layout-editor.com/#/gists/20a08aa7f56c7da7c69ccb951c14491e

![](https://kle-render.herokuapp.com/api/20a08aa7f56c7da7c69ccb951c14491e?1)

**Comment by dejanr** [comment]
@joric impressive work with BLE! I am owning one Atreus so far, and was looking for BLE keyboard. And your layout looks impressive.

Where you got those tin profile keys and key caps?

Keep up the great work, looking forward into making one for myself!

**Comment by joric** [comment]
@dejanr well thankyou! it's [Jian](https://redd.it/apfxsj) layout actually.

Those switches are Kailh LP, keycaps are from here I guess ($14, free shipping) https://www.aliexpress.com/item//32915900901.html

I don't like low profile caps, they're really uncomfortable, for the bottom row I'd rather prefer flipped R1.

**Comment by joric** [comment]
@geoah this project now has a new rgb firmware and public wiki https://github.com/joric/jorian/wiki
