### ISSUE TITLE
Question: Kit, BOM, or more info? 

### ISSUE THREAD

**Issue by MikaelElkiaer** [joric/jorian#3]
Heya, I really like this board, but I am having some troubles figuring out exactly what is needed. Is there a kit to be found anywhere? Or a detailed BOM?

Also, I'd like to omit the pinky and extra thumb bits, is that straightforward, or will it ef up some connections?

**Comment by joric** [comment]
There's no much sense in this board anymore, 100x100 boards don't really cost $2 anymore and JLCPCB would ask extra for the number of slots and it has multiple flaws such as RGB leak, etc. There's everything in the wiki. Extra bits are mandatory. I don't really remember the layout but the thumb bit probably has data in and data out and the thumb bits are all interconnected also. If you need a crippled keyboard just make an original mitosis (it's borderline unusable though because of the two level thumb cluster)

**Comment by MikaelElkiaer** [comment]
Oh, thanks for clearing that up. Shifting my gaze to Ferris then.
